import Head from "next/head";
import Login from "../components/Section/Login";
import Demo from "../components/Section/Demo";
import Register from "../components/Section/Register";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tipping App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="section">
          <div className="container | u-px-5 u-py-5">
            <div className="hero | u-bg-neutral-500 u-mx-auto | u-flex u-items-center u-justify-between u-gap-2">
              <div className="hero__item hero__item--start |  | u-flex  u-justify-center">
                <Login />
                {/* <Register /> */}
              </div>
              <div className="hero__item hero__item--end | u-flex  u-justify-center">
                <Demo />
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
