import Head from "next/head";
import Login from "../components/Section/Login";
import Register from "../components/Section/Register";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tipping App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="section">
          <div className="container | u-bg-neutral-400 u-px-5 u-py-5">
            <div className="hero | u-mx-auto | u-flex u-items-center u-justify-between u-gap-2">
              <div className="hero__item hero__item--start | u-bg-neutral-500 | u-flex u-items-end">
                <Login />
                {/* <Register /> */}
              </div>
              <div className="hero__item hero__item--end | u-bg-neutral-700 | u-flex  u-items-end">
                <div>
                  <p>Sign-in with Guest account</p>
                  <button className="btn btn--cta | u-mb-1 u-ml-2">
                    Guest
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
